"use client";

import { motion } from "framer-motion";
import { AlertTriangle, Zap, Camera, Eye, Clock, ShieldAlert } from "lucide-react";
import { PageHeader } from "@/components/shared/page-header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { mockAIAlerts } from "@/data/mock";
import { formatRelativeTime } from "@/lib/utils";
import { staggerContainer, staggerItem } from "@/lib/constants";

export default function AIAlertsPage() {
  return (
    <div className="space-y-6">
      <PageHeader
        title="AI Safety Alerts"
        description="Review real-time detections and predictive warnings generated by SafeDrive AI."
        breadcrumbs={[
          { label: "Home", href: "/driver" },
          { label: "AI Alerts" },
        ]}
      />

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6">
        <Card className="bg-gradient-to-br from-amber-500/10 to-transparent border-amber-500/20">
          <CardContent className="p-6 flex flex-col items-center text-center gap-2">
            <Zap className="h-8 w-8 text-amber-500 mb-2" />
            <h3 className="text-2xl font-bold text-text-primary">12</h3>
            <p className="text-sm text-text-secondary">Alerts This Week</p>
          </CardContent>
        </Card>
        <Card className="bg-gradient-to-br from-red-500/10 to-transparent border-red-500/20">
          <CardContent className="p-6 flex flex-col items-center text-center gap-2">
            <ShieldAlert className="h-8 w-8 text-red-500 mb-2" />
            <h3 className="text-2xl font-bold text-text-primary">2</h3>
            <p className="text-sm text-text-secondary">Critical Warnings</p>
          </CardContent>
        </Card>
        <Card className="bg-gradient-to-br from-blue-500/10 to-transparent border-blue-500/20">
          <CardContent className="p-6 flex flex-col items-center text-center gap-2">
            <Eye className="h-8 w-8 text-blue-500 mb-2" />
            <h3 className="text-2xl font-bold text-text-primary">98%</h3>
            <p className="text-sm text-text-secondary">AI Confidence Avg</p>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <AlertTriangle className="h-5 w-5 text-amber-400" />
            Recent AI Detections
          </CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          <motion.div variants={staggerContainer} initial="initial" animate="animate" className="divide-y divide-border-subtle">
            {mockAIAlerts.map((alert) => (
              <motion.div key={alert.id} variants={staggerItem} className="p-4 sm:p-6 hover:bg-bg-elevated transition-colors flex flex-col sm:flex-row gap-4 sm:items-center">
                <div className={`h-12 w-12 rounded-full flex items-center justify-center shrink-0 ${
                  alert.severity === "critical" ? "bg-red-500/20 text-red-500" :
                  alert.severity === "warning" ? "bg-amber-500/20 text-amber-500" :
                  "bg-blue-500/20 text-blue-500"
                }`}>
                  {alert.type === "drowsiness" ? <Eye className="h-6 w-6" /> : 
                   alert.type === "distraction" ? <AlertTriangle className="h-6 w-6" /> : 
                   <Zap className="h-6 w-6" />}
                </div>
                
                <div className="flex-1 space-y-1">
                  <div className="flex items-center gap-2">
                    <h4 className="text-base font-medium text-text-primary capitalize">{alert.type.replace("_", " ")} Detected</h4>
                    <Badge variant={alert.severity === "critical" ? "danger" : alert.severity === "warning" ? "warning" : "default"}>
                      {alert.severity}
                    </Badge>
                  </div>
                  <p className="text-sm text-text-secondary">{alert.message}</p>
                  <div className="flex items-center gap-4 text-xs text-text-muted pt-1">
                    <span className="flex items-center gap-1"><Clock className="h-3 w-3" /> {formatRelativeTime(alert.createdAt)}</span>
                    <span className="flex items-center gap-1"><Zap className="h-3 w-3" /> Confidence: {Math.round(alert.confidence * 100)}%</span>
                  </div>
                </div>

                <div className="shrink-0 pt-2 sm:pt-0">
                  <Button variant="outline" size="sm" className="w-full sm:w-auto">
                    <Camera className="h-4 w-4 mr-2" /> View Snapshot
                  </Button>
                </div>
              </motion.div>
            ))}
          </motion.div>
        </CardContent>
      </Card>
    </div>
  );
}
